services:
  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: ./main

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data
